// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using telemetry_ingestion.Data;

#nullable disable

namespace telemetry_ingestion.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225135831_InitialFullSchema")]
    partial class InitialFullSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("telemetry_ingestion.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("telemetry_ingestion.Models.TelemetryRecordBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("integer");

                    b.Property<byte>("MessageType")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("RawPayload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("TelemetryRecordBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("telemetry_ingestion.Models.SpeedRecord", b =>
                {
                    b.HasBaseType("telemetry_ingestion.Models.TelemetryRecordBase");

                    b.Property<bool>("Running")
                        .HasColumnType("boolean");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.ToTable("SpeedRecords", (string)null);
                });

            modelBuilder.Entity("telemetry_ingestion.Models.TemperatureRecord", b =>
                {
                    b.HasBaseType("telemetry_ingestion.Models.TelemetryRecordBase");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.ToTable("TemperatureRecords", (string)null);
                });

            modelBuilder.Entity("telemetry_ingestion.Models.VibrationRecord", b =>
                {
                    b.HasBaseType("telemetry_ingestion.Models.TelemetryRecordBase");

                    b.Property<int>("Amplitude")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.ToTable("VibrationRecords", (string)null);
                });

            modelBuilder.Entity("telemetry_ingestion.Models.TelemetryRecordBase", b =>
                {
                    b.HasOne("telemetry_ingestion.Models.Device", "Device")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("telemetry_ingestion.Models.SpeedRecord", b =>
                {
                    b.HasOne("telemetry_ingestion.Models.TelemetryRecordBase", null)
                        .WithOne()
                        .HasForeignKey("telemetry_ingestion.Models.SpeedRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("telemetry_ingestion.Models.TemperatureRecord", b =>
                {
                    b.HasOne("telemetry_ingestion.Models.TelemetryRecordBase", null)
                        .WithOne()
                        .HasForeignKey("telemetry_ingestion.Models.TemperatureRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("telemetry_ingestion.Models.VibrationRecord", b =>
                {
                    b.HasOne("telemetry_ingestion.Models.TelemetryRecordBase", null)
                        .WithOne()
                        .HasForeignKey("telemetry_ingestion.Models.VibrationRecord", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("telemetry_ingestion.Models.Device", b =>
                {
                    b.Navigation("TelemetryRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
